vectorDB:
    class: Qdrant
    kwargs:
        port: 6333
        collection_name: chat-eur-lex

    retriever_args: 
        search_type: similarity_score_threshold
        search_kwargs: 
            k: 5
            score_threshold: 0.6

embeddings: 
    class: OpenAIEmbeddings
    kwargs:
        openai_api_key: [key]
        model: text-embedding-ada-002


llm: 
    class: ChatOpenAI
    use_context_function: True
    kwargs:
        openai_api_key: [key]
        model_name: gpt-4
        temperature: 0.0


chatDB:
    class: FileChatMessageHistory
    kwargs:
        output_path: /path/to/chat-eur-lex/chat/output

max_history_messages: 5