vectorDB:
    class: Qdrant
    kwargs:
        url: ""
        api_key: ""
        port: 6333
        collection_name: chat-eur-lex

    retriever_args: 
        search_type: mmr
        search_kwargs: 
            k: 10
            fetch_k: 300
            lambda_mult: 0.8
    
    rerank:
        use_rerank: false
        class: CohereRerank
        kwargs:
            cohere_api_key: ""
            model: rerank-multilingual-v3.0
            top_n: 10

embeddings: 
    class: OpenAIEmbeddings
    kwargs:
        model: text-embedding-ada-002


llm: 
    class: ChatOpenAI
    use_context_function: True
    max_context_size: 6000
    kwargs:
        model_name: gpt-4
        temperature: 0.8


chatDB:
    class: FileChatMessageHistory
    kwargs:
        output_path: /path/to/chat-eur-lex/chat/output

max_history_messages: 5