embeddings:
  class: OpenAIEmbeddings
  kwargs:
    openai_api_key: "[openai_api_key]"
    model: "text-embedding-ada-002"

vectorDB:
  class: Qdrant
  kwargs:
    port: 6333
    url: http://qdrant:6333/
    collection_name: chat-eur-lex

splitter:
  class: LineSplitter
  kwargs:
    chunk_size: 10
    chunk_overlap: 3
    separator: "\n"
