akoma_ntoso_dataset_path: path/to/akn/folder/3*.xml

embeddings:
  class: OpenAIEmbeddings
  kwargs:
    openai_api_key: "[openai_api_key]"
    model: "text-embedding-ada-002"

vectorDB:
  akn_document_token_size: 1000
  class: Qdrant
  kwargs:
    port: 6333
    url: http://qdrant
    collection_name: chat-eur-lex

splitter:
  class: LineSplitter
  kwargs:
    chunk_size: 10
    chunk_overlap: 3
    separator: "\n"
